### ISSUE TITLE
more gentle error reporting

### ISSUE THREAD

**Issue by podhmo** [podhmo/reflect-openapi#19]

**Comment by podhmo** [comment]
```
panic: (shape.Interface) 0xc000303680

goroutine 1 [running]:
github.com/podhmo/reflect-openapi.notImplementedYet(...)
        /go/src/github.com/podhmo/reflect-openapi/visitor.go:297
github.com/podhmo/reflect-openapi.(*Transformer).Transform(0xc0000793b0, 0x15eb0c0, 0xc000303680, 0x5, 0x0)
        /go/src/github.com/podhmo/reflect-openapi/visitor.go:291 +0x2948
github.com/podhmo/reflect-openapi.(*Transformer).Transform(0xc0000793b0, 0x15eb180, 0xc0003101c0, 0xc0003101c0, 0xc000308010)
        /go/src/github.com/podhmo/reflect-openapi/visitor.go:173 +0x22c6
github.com/podhmo/reflect-openapi.(*Visitor).VisitType(0xc000079440, 0x14e85a0, 0xc00000e600, 0x0, 0x0, 0x0, 0xc00000e600)
        /go/src/github.com/podhmo/reflect-openapi/visitor.go:49 +0x68
github.com/podhmo/reflect-openapi.(*Config).BuildDoc(0xc0002f9ea8, 0x15e7ca0, 0xc000122000, 0xc0002efe58, 0x1, 0x1, 0x0)
        /go/src/github.com/podhmo/reflect-openapi/api.go:84 +0x157
main.run(0x1007ec5, 0xc00010e058)
        /Users/podhmo/daily/20201010/example_go/10todo/main.go:123 +0x319
main.main()
        /Users/podhmo/daily/20201010/example_go/10todo/main.go:89 +0x26
exit status 2
```
